// <auto-generated />
using FAQ.App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FAQ.App.Migrations
{
    [DbContext(typeof(FAQcontext))]
    partial class FAQcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FAQ.App.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "gen",
                            Name = "General"
                        },
                        new
                        {
                            Id = "his",
                            Name = "Hisotry"
                        });
                });

            modelBuilder.Entity("FAQ.App.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQ");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A CSS framework for creating responsive web apps for multipe screen sizes.",
                            CategoryId = "gen",
                            Question = "What is Bootstrap?",
                            TopicId = "bs"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "In 2011.",
                            CategoryId = "his",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bs"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "gen",
                            Question = "What is C#?",
                            TopicId = "cs"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "In 2002.",
                            CategoryId = "his",
                            Question = "When was C# first released?",
                            TopicId = "cs"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "A general purpose scipting language that executes in a web browser.",
                            CategoryId = "gen",
                            Question = "What is JavaScript?",
                            TopicId = "js"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "In 1995.",
                            CategoryId = "his",
                            Question = "When was JavaScript first released?",
                            TopicId = "js"
                        });
                });

            modelBuilder.Entity("FAQ.App.Models.Topic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topic");

                    b.HasData(
                        new
                        {
                            Id = "cs",
                            Name = "C#"
                        },
                        new
                        {
                            Id = "bs",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = "js",
                            Name = "Javascript"
                        });
                });

            modelBuilder.Entity("FAQ.App.Models.FAQ", b =>
                {
                    b.HasOne("FAQ.App.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FAQ.App.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");
                });
#pragma warning restore 612, 618
        }
    }
}
